# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

#エリア一覧
@hokaido = Prefecture.create(name: '北海道', order_num: 1)
  Municipality.create(name: '札幌市中央区', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '札幌市北区', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '札幌市東区', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '札幌市白石区', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '札幌市豊平区', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '札幌市南区', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '札幌市西区', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '札幌市厚別区', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '札幌市手稲区', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '札幌市清田区', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '函館市', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '小樽市', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '旭川市', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '室蘭市', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '釧路市', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '帯広市', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '北見市', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '夕張市', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '岩見沢市', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '網走市', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '留萌市', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '苫小牧市', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '稚内市', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '美唄市', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '芦別市', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '江別市', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '赤平市', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '紋別市', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '士別市', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '名寄市', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '三笠市', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '根室市', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '千歳市', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '滝川市', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '砂川市', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '歌志内市', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '深川市', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '富良野市', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '登別市', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '恵庭市', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '伊達市', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '北広島市', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '石狩市', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '北斗市', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '当別町', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '新篠津村', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '松前町', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '福島町', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '知内町', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '木古内町', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '七飯町', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '鹿部町', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '森町', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '八雲町', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '長万部町', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '江差町', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '上ノ国町', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '厚沢部町', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '乙部町', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '奥尻町', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '今金町', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: 'せたな町', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '島牧村', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '寿都町', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '黒松内町', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '蘭越町', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: 'ニセコ町', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '真狩村', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '留寿都村', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '喜茂別町', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '京極町', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '倶知安町', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '共和町', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '岩内町', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '泊村', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '神恵内村', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '積丹町', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '古平町', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '仁木町', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '余市町', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '赤井川村', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '南幌町', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '奈井江町', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '上砂川町', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '由仁町', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '長沼町', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '栗山町', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '月形町', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '浦臼町', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '新十津川町', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '妹背牛町', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '秩父別町', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '雨竜町', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '北竜町', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '沼田町', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '鷹栖町', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '東神楽町', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '当麻町', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '比布町', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '愛別町', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '上川町', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '東川町', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '美瑛町', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '上富良野町', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '中富良野町', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '南富良野町', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '占冠村', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '和寒町', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '剣淵町', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '下川町', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '美深町', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '音威子府村', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '中川町', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '幌加内町', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '増毛町', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '小平町', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '苫前町', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '羽幌町', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '初山別村', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '遠別町', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '天塩町', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '猿払村', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '浜頓別町', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '中頓別町', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '枝幸町', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '豊富町', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '礼文町', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '利尻町', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '利尻富士町', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '幌延町', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '美幌町', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '津別町', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '斜里町', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '清里町', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '小清水町', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '訓子府町', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '置戸町', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '佐呂間町', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '遠軽町', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '湧別町', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '滝上町', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '興部町', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '西興部村', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '雄武町', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '大空町', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '豊浦町', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '壮瞥町', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '白老町', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '厚真町', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '洞爺湖町', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '安平町', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: 'むかわ町', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '日高町', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '平取町', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '新冠町', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '浦河町', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '様似町', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: 'えりも町', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '新ひだか町', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '音更町', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '士幌町', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '上士幌町', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '鹿追町', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '新得町', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '清水町', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '芽室町', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '中札内村', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '更別村', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '大樹町', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '広尾町', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '幕別町', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '池田町', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '豊頃町', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '本別町', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '足寄町', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '陸別町', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '浦幌町', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '釧路町', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '厚岸町', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '浜中町', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '標茶町', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '弟子屈町', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '鶴居村', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '白糠町', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '別海町', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '中標津町', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '標津町', order_num: 1, prefecture_id: @hokaido.id)
  Municipality.create(name: '羅臼町', order_num: 1, prefecture_id: @hokaido.id)

@aomori = Prefecture.create(name: '青森', order_num: 2)
  Municipality.create(name: '青森市', order_num: 1, prefecture_id: @aomori.id)
  Municipality.create(name: '弘前市', order_num: 1, prefecture_id: @aomori.id)
  Municipality.create(name: '八戸市', order_num: 1, prefecture_id: @aomori.id)
  Municipality.create(name: '黒石市', order_num: 1, prefecture_id: @aomori.id)
  Municipality.create(name: '五所川原市', order_num: 1, prefecture_id: @aomori.id)
  Municipality.create(name: '十和田市', order_num: 1, prefecture_id: @aomori.id)
  Municipality.create(name: '三沢市', order_num: 1, prefecture_id: @aomori.id)
  Municipality.create(name: 'むつ市', order_num: 1, prefecture_id: @aomori.id)
  Municipality.create(name: 'つがる市', order_num: 1, prefecture_id: @aomori.id)
  Municipality.create(name: '平川市', order_num: 1, prefecture_id: @aomori.id)
  Municipality.create(name: '平内町', order_num: 1, prefecture_id: @aomori.id)
  Municipality.create(name: '今別町', order_num: 1, prefecture_id: @aomori.id)
  Municipality.create(name: '蓬田村', order_num: 1, prefecture_id: @aomori.id)
  Municipality.create(name: '外ヶ浜町', order_num: 1, prefecture_id: @aomori.id)
  Municipality.create(name: '鰺ヶ沢町', order_num: 1, prefecture_id: @aomori.id)
  Municipality.create(name: '深浦町', order_num: 1, prefecture_id: @aomori.id)
  Municipality.create(name: '西目屋村', order_num: 1, prefecture_id: @aomori.id)
  Municipality.create(name: '藤崎町', order_num: 1, prefecture_id: @aomori.id)
  Municipality.create(name: '大鰐町', order_num: 1, prefecture_id: @aomori.id)
  Municipality.create(name: '田舎館村', order_num: 1, prefecture_id: @aomori.id)
  Municipality.create(name: '板柳町', order_num: 1, prefecture_id: @aomori.id)
  Municipality.create(name: '鶴田町', order_num: 1, prefecture_id: @aomori.id)
  Municipality.create(name: '中泊町', order_num: 1, prefecture_id: @aomori.id)
  Municipality.create(name: '野辺地町', order_num: 1, prefecture_id: @aomori.id)
  Municipality.create(name: '七戸町', order_num: 1, prefecture_id: @aomori.id)
  Municipality.create(name: '六戸町', order_num: 1, prefecture_id: @aomori.id)
  Municipality.create(name: '横浜町', order_num: 1, prefecture_id: @aomori.id)
  Municipality.create(name: '東北町', order_num: 1, prefecture_id: @aomori.id)
  Municipality.create(name: '六ヶ所村', order_num: 1, prefecture_id: @aomori.id)
  Municipality.create(name: 'おいらせ町', order_num: 1, prefecture_id: @aomori.id)
  Municipality.create(name: '大間町', order_num: 1, prefecture_id: @aomori.id)
  Municipality.create(name: '東通村', order_num: 1, prefecture_id: @aomori.id)
  Municipality.create(name: '風間浦村', order_num: 1, prefecture_id: @aomori.id)
  Municipality.create(name: '佐井村', order_num: 1, prefecture_id: @aomori.id)
  Municipality.create(name: '三戸町', order_num: 1, prefecture_id: @aomori.id)
  Municipality.create(name: '五戸町', order_num: 1, prefecture_id: @aomori.id)
  Municipality.create(name: '田子町', order_num: 1, prefecture_id: @aomori.id)
  Municipality.create(name: '南部町', order_num: 1, prefecture_id: @aomori.id)
  Municipality.create(name: '階上町', order_num: 1, prefecture_id: @aomori.id)
  Municipality.create(name: '新郷村', order_num: 1, prefecture_id: @aomori.id)

@iwate = Prefecture.create(name: '岩手', order_num: 3)
  Municipality.create(name: '盛岡市', order_num: 1, prefecture_id: @iwate.id)
  Municipality.create(name: '宮古市', order_num: 1, prefecture_id: @iwate.id)
  Municipality.create(name: '大船渡市', order_num: 1, prefecture_id: @iwate.id)
  Municipality.create(name: '花巻市', order_num: 1, prefecture_id: @iwate.id)
  Municipality.create(name: '北上市', order_num: 1, prefecture_id: @iwate.id)
  Municipality.create(name: '久慈市', order_num: 1, prefecture_id: @iwate.id)
  Municipality.create(name: '遠野市', order_num: 1, prefecture_id: @iwate.id)
  Municipality.create(name: '一関市', order_num: 1, prefecture_id: @iwate.id)
  Municipality.create(name: '陸前高田市', order_num: 1, prefecture_id: @iwate.id)
  Municipality.create(name: '釜石市', order_num: 1, prefecture_id: @iwate.id)
  Municipality.create(name: '二戸市', order_num: 1, prefecture_id: @iwate.id)
  Municipality.create(name: '八幡平市', order_num: 1, prefecture_id: @iwate.id)
  Municipality.create(name: '奥州市', order_num: 1, prefecture_id: @iwate.id)
  Municipality.create(name: '滝沢市', order_num: 1, prefecture_id: @iwate.id)
  Municipality.create(name: '雫石町', order_num: 1, prefecture_id: @iwate.id)
  Municipality.create(name: '葛巻町', order_num: 1, prefecture_id: @iwate.id)
  Municipality.create(name: '岩手町', order_num: 1, prefecture_id: @iwate.id)
  Municipality.create(name: '紫波町', order_num: 1, prefecture_id: @iwate.id)
  Municipality.create(name: '矢巾町', order_num: 1, prefecture_id: @iwate.id)
  Municipality.create(name: '西和賀町', order_num: 1, prefecture_id: @iwate.id)
  Municipality.create(name: '金ケ崎町', order_num: 1, prefecture_id: @iwate.id)
  Municipality.create(name: '平泉町', order_num: 1, prefecture_id: @iwate.id)
  Municipality.create(name: '住田町', order_num: 1, prefecture_id: @iwate.id)
  Municipality.create(name: '大槌町', order_num: 1, prefecture_id: @iwate.id)
  Municipality.create(name: '山田町', order_num: 1, prefecture_id: @iwate.id)
  Municipality.create(name: '岩泉町', order_num: 1, prefecture_id: @iwate.id)
  Municipality.create(name: '田野畑村', order_num: 1, prefecture_id: @iwate.id)
  Municipality.create(name: '普代村', order_num: 1, prefecture_id: @iwate.id)
  Municipality.create(name: '軽米町', order_num: 1, prefecture_id: @iwate.id)
  Municipality.create(name: '野田村', order_num: 1, prefecture_id: @iwate.id)
  Municipality.create(name: '九戸村', order_num: 1, prefecture_id: @iwate.id)
  Municipality.create(name: '洋野町', order_num: 1, prefecture_id: @iwate.id)
  Municipality.create(name: '一戸町', order_num: 1, prefecture_id: @iwate.id)

@miyagi = Prefecture.create(name: '宮城', order_num: 4)
  Municipality.create(name: '仙台市青葉区', order_num: 1, prefecture_id: @miyagi.id)
  Municipality.create(name: '仙台市宮城野区', order_num: 1, prefecture_id: @miyagi.id)
  Municipality.create(name: '仙台市若林区', order_num: 1, prefecture_id: @miyagi.id)
  Municipality.create(name: '仙台市太白区', order_num: 1, prefecture_id: @miyagi.id)
  Municipality.create(name: '仙台市泉区', order_num: 1, prefecture_id: @miyagi.id)
  Municipality.create(name: '石巻市', order_num: 1, prefecture_id: @miyagi.id)
  Municipality.create(name: '塩竈市', order_num: 1, prefecture_id: @miyagi.id)
  Municipality.create(name: '気仙沼市', order_num: 1, prefecture_id: @miyagi.id)
  Municipality.create(name: '白石市', order_num: 1, prefecture_id: @miyagi.id)
  Municipality.create(name: '名取市', order_num: 1, prefecture_id: @miyagi.id)
  Municipality.create(name: '角田市', order_num: 1, prefecture_id: @miyagi.id)
  Municipality.create(name: '多賀城市', order_num: 1, prefecture_id: @miyagi.id)
  Municipality.create(name: '岩沼市', order_num: 1, prefecture_id: @miyagi.id)
  Municipality.create(name: '登米市', order_num: 1, prefecture_id: @miyagi.id)
  Municipality.create(name: '栗原市', order_num: 1, prefecture_id: @miyagi.id)
  Municipality.create(name: '東松島市', order_num: 1, prefecture_id: @miyagi.id)
  Municipality.create(name: '大崎市', order_num: 1, prefecture_id: @miyagi.id)
  Municipality.create(name: '富谷市', order_num: 1, prefecture_id: @miyagi.id)
  Municipality.create(name: '蔵王町', order_num: 1, prefecture_id: @miyagi.id)
  Municipality.create(name: '七ヶ宿町', order_num: 1, prefecture_id: @miyagi.id)
  Municipality.create(name: '大河原町', order_num: 1, prefecture_id: @miyagi.id)
  Municipality.create(name: '村田町', order_num: 1, prefecture_id: @miyagi.id)
  Municipality.create(name: '柴田町', order_num: 1, prefecture_id: @miyagi.id)
  Municipality.create(name: '川崎町', order_num: 1, prefecture_id: @miyagi.id)
  Municipality.create(name: '丸森町', order_num: 1, prefecture_id: @miyagi.id)
  Municipality.create(name: '亘理町', order_num: 1, prefecture_id: @miyagi.id)
  Municipality.create(name: '山元町', order_num: 1, prefecture_id: @miyagi.id)
  Municipality.create(name: '松島町', order_num: 1, prefecture_id: @miyagi.id)
  Municipality.create(name: '七ヶ浜町', order_num: 1, prefecture_id: @miyagi.id)
  Municipality.create(name: '利府町', order_num: 1, prefecture_id: @miyagi.id)
  Municipality.create(name: '大和町', order_num: 1, prefecture_id: @miyagi.id)
  Municipality.create(name: '大郷町', order_num: 1, prefecture_id: @miyagi.id)
  Municipality.create(name: '大衡村', order_num: 1, prefecture_id: @miyagi.id)
  Municipality.create(name: '色麻町', order_num: 1, prefecture_id: @miyagi.id)
  Municipality.create(name: '加美町', order_num: 1, prefecture_id: @miyagi.id)
  Municipality.create(name: '涌谷町', order_num: 1, prefecture_id: @miyagi.id)
  Municipality.create(name: '美里町', order_num: 1, prefecture_id: @miyagi.id)
  Municipality.create(name: '女川町', order_num: 1, prefecture_id: @miyagi.id)
  Municipality.create(name: '南三陸町', order_num: 1, prefecture_id: @miyagi.id)

Prefecture.create(name: '秋田', order_num: 5)
Prefecture.create(name: '山形', order_num: 6)
Prefecture.create(name: '福島', order_num: 7)
Prefecture.create(name: '茨城', order_num: 8)
Prefecture.create(name: '栃木', order_num: 9)
Prefecture.create(name: '群馬', order_num: 10)
Prefecture.create(name: '埼玉', order_num: 11)
Prefecture.create(name: '千葉', order_num: 12)
@tokyo = Prefecture.create(name: '東京', order_num: 13)
  Municipality.create(name: '千代田区', order_num: 1, prefecture_id: @tokyo.id)
  Municipality.create(name: '中央区', order_num: 1, prefecture_id: @tokyo.id)
  Municipality.create(name: '港区', order_num: 1, prefecture_id: @tokyo.id)
  Municipality.create(name: '新宿区', order_num: 1, prefecture_id: @tokyo.id)
  Municipality.create(name: '文京区', order_num: 1, prefecture_id: @tokyo.id)
  Municipality.create(name: '台東区', order_num: 1, prefecture_id: @tokyo.id)
  Municipality.create(name: '墨田区', order_num: 1, prefecture_id: @tokyo.id)
  Municipality.create(name: '江東区', order_num: 1, prefecture_id: @tokyo.id)
  Municipality.create(name: '品川区', order_num: 1, prefecture_id: @tokyo.id)
  Municipality.create(name: '目黒区', order_num: 1, prefecture_id: @tokyo.id)
  Municipality.create(name: '大田区', order_num: 1, prefecture_id: @tokyo.id)
  Municipality.create(name: '世田谷区', order_num: 1, prefecture_id: @tokyo.id)
  Municipality.create(name: '渋谷区', order_num: 1, prefecture_id: @tokyo.id)
  Municipality.create(name: '中野区', order_num: 1, prefecture_id: @tokyo.id)
  Municipality.create(name: '杉並区', order_num: 1, prefecture_id: @tokyo.id)
  Municipality.create(name: '豊島区', order_num: 1, prefecture_id: @tokyo.id)
  Municipality.create(name: '北区', order_num: 1, prefecture_id: @tokyo.id)
  Municipality.create(name: '荒川区', order_num: 1, prefecture_id: @tokyo.id)
  Municipality.create(name: '板橋区', order_num: 1, prefecture_id: @tokyo.id)
  Municipality.create(name: '練馬区', order_num: 1, prefecture_id: @tokyo.id)
  Municipality.create(name: '足立区', order_num: 1, prefecture_id: @tokyo.id)
  Municipality.create(name: '葛飾区', order_num: 1, prefecture_id: @tokyo.id)
  Municipality.create(name: '江戸川区', order_num: 1, prefecture_id: @tokyo.id)
  Municipality.create(name: '八王子市', order_num: 1, prefecture_id: @tokyo.id)
  Municipality.create(name: '立川市', order_num: 1, prefecture_id: @tokyo.id)
  Municipality.create(name: '武蔵野市', order_num: 1, prefecture_id: @tokyo.id)
  Municipality.create(name: '三鷹市', order_num: 1, prefecture_id: @tokyo.id)
  Municipality.create(name: '青梅市', order_num: 1, prefecture_id: @tokyo.id)
  Municipality.create(name: '府中市', order_num: 1, prefecture_id: @tokyo.id)
  Municipality.create(name: '昭島市', order_num: 1, prefecture_id: @tokyo.id)
  Municipality.create(name: '調布市', order_num: 1, prefecture_id: @tokyo.id)
  Municipality.create(name: '町田市', order_num: 1, prefecture_id: @tokyo.id)
  Municipality.create(name: '小金井市', order_num: 1, prefecture_id: @tokyo.id)
  Municipality.create(name: '小平市', order_num: 1, prefecture_id: @tokyo.id)
  Municipality.create(name: '日野市', order_num: 1, prefecture_id: @tokyo.id)
  Municipality.create(name: '東村山市', order_num: 1, prefecture_id: @tokyo.id)
  Municipality.create(name: '国分寺市', order_num: 1, prefecture_id: @tokyo.id)
  Municipality.create(name: '国立市', order_num: 1, prefecture_id: @tokyo.id)
  Municipality.create(name: '福生市', order_num: 1, prefecture_id: @tokyo.id)
  Municipality.create(name: '狛江市', order_num: 1, prefecture_id: @tokyo.id)
  Municipality.create(name: '東大和市', order_num: 1, prefecture_id: @tokyo.id)
  Municipality.create(name: '清瀬市', order_num: 1, prefecture_id: @tokyo.id)
  Municipality.create(name: '東久留米市', order_num: 1, prefecture_id: @tokyo.id)
  Municipality.create(name: '武蔵村山市', order_num: 1, prefecture_id: @tokyo.id)
  Municipality.create(name: '多摩市', order_num: 1, prefecture_id: @tokyo.id)
  Municipality.create(name: '稲城市', order_num: 1, prefecture_id: @tokyo.id)
  Municipality.create(name: '羽村市', order_num: 1, prefecture_id: @tokyo.id)
  Municipality.create(name: 'あきる野市', order_num: 1, prefecture_id: @tokyo.id)
  Municipality.create(name: '西東京市', order_num: 1, prefecture_id: @tokyo.id)
  Municipality.create(name: '瑞穂町', order_num: 1, prefecture_id: @tokyo.id)
  Municipality.create(name: '日の出町', order_num: 1, prefecture_id: @tokyo.id)
  Municipality.create(name: '檜原村', order_num: 1, prefecture_id: @tokyo.id)
  Municipality.create(name: '奥多摩町', order_num: 1, prefecture_id: @tokyo.id)
  Municipality.create(name: '大島町', order_num: 1, prefecture_id: @tokyo.id)
  Municipality.create(name: '利島村', order_num: 1, prefecture_id: @tokyo.id)
  Municipality.create(name: '新島村', order_num: 1, prefecture_id: @tokyo.id)
  Municipality.create(name: '神津島村', order_num: 1, prefecture_id: @tokyo.id)
  Municipality.create(name: '三宅村', order_num: 1, prefecture_id: @tokyo.id)
  Municipality.create(name: '御蔵島村', order_num: 1, prefecture_id: @tokyo.id)
  Municipality.create(name: '八丈町', order_num: 1, prefecture_id: @tokyo.id)
  Municipality.create(name: '青ヶ島村', order_num: 1, prefecture_id: @tokyo.id)
  Municipality.create(name: '小笠原村', order_num: 1, prefecture_id: @tokyo.id)


Prefecture.create(name: '神奈川', order_num: 14)
Prefecture.create(name: '新潟', order_num: 15)
Prefecture.create(name: '富山', order_num: 16)
Prefecture.create(name: '石川', order_num: 17)
Prefecture.create(name: '福井', order_num: 18)
Prefecture.create(name: '山梨', order_num: 19)
Prefecture.create(name: '長野', order_num: 20)
Prefecture.create(name: '岐阜', order_num: 21)
Prefecture.create(name: '静岡', order_num: 22)
@aichi = Prefecture.create(name: '愛知', order_num: 23)
  Municipality.create(name: '名古屋市千種区', order_num: 1, prefecture_id: @aichi.id)
  Municipality.create(name: '名古屋市東区', order_num: 1, prefecture_id: @aichi.id)
  Municipality.create(name: '名古屋市北区', order_num: 1, prefecture_id: @aichi.id)
  Municipality.create(name: '名古屋市西区', order_num: 1, prefecture_id: @aichi.id)
  Municipality.create(name: '名古屋市中村区', order_num: 1, prefecture_id: @aichi.id)
  Municipality.create(name: '名古屋市中区', order_num: 1, prefecture_id: @aichi.id)
  Municipality.create(name: '名古屋市昭和区', order_num: 1, prefecture_id: @aichi.id)
  Municipality.create(name: '名古屋市瑞穂区', order_num: 1, prefecture_id: @aichi.id)
  Municipality.create(name: '名古屋市熱田区', order_num: 1, prefecture_id: @aichi.id)
  Municipality.create(name: '名古屋市中川区', order_num: 1, prefecture_id: @aichi.id)
  Municipality.create(name: '名古屋市港区', order_num: 1, prefecture_id: @aichi.id)
  Municipality.create(name: '名古屋市南区', order_num: 1, prefecture_id: @aichi.id)
  Municipality.create(name: '名古屋市守山区', order_num: 1, prefecture_id: @aichi.id)
  Municipality.create(name: '名古屋市緑区', order_num: 1, prefecture_id: @aichi.id)
  Municipality.create(name: '名古屋市名東区', order_num: 1, prefecture_id: @aichi.id)
  Municipality.create(name: '名古屋市天白区', order_num: 1, prefecture_id: @aichi.id)
  Municipality.create(name: '豊橋市', order_num: 1, prefecture_id: @aichi.id)
  Municipality.create(name: '岡崎市', order_num: 1, prefecture_id: @aichi.id)
  Municipality.create(name: '一宮市', order_num: 1, prefecture_id: @aichi.id)
  Municipality.create(name: '瀬戸市', order_num: 1, prefecture_id: @aichi.id)
  Municipality.create(name: '半田市', order_num: 1, prefecture_id: @aichi.id)
  Municipality.create(name: '春日井市', order_num: 1, prefecture_id: @aichi.id)
  Municipality.create(name: '豊川市', order_num: 1, prefecture_id: @aichi.id)
  Municipality.create(name: '津島市', order_num: 1, prefecture_id: @aichi.id)
  Municipality.create(name: '碧南市', order_num: 1, prefecture_id: @aichi.id)
  Municipality.create(name: '刈谷市', order_num: 1, prefecture_id: @aichi.id)
  Municipality.create(name: '豊田市', order_num: 1, prefecture_id: @aichi.id)
  Municipality.create(name: '安城市', order_num: 1, prefecture_id: @aichi.id)
  Municipality.create(name: '西尾市', order_num: 1, prefecture_id: @aichi.id)
  Municipality.create(name: '蒲郡市', order_num: 1, prefecture_id: @aichi.id)
  Municipality.create(name: '犬山市', order_num: 1, prefecture_id: @aichi.id)
  Municipality.create(name: '常滑市', order_num: 1, prefecture_id: @aichi.id)
  Municipality.create(name: '江南市', order_num: 1, prefecture_id: @aichi.id)
  Municipality.create(name: '小牧市', order_num: 1, prefecture_id: @aichi.id)
  Municipality.create(name: '稲沢市', order_num: 1, prefecture_id: @aichi.id)
  Municipality.create(name: '新城市', order_num: 1, prefecture_id: @aichi.id)
  Municipality.create(name: '東海市', order_num: 1, prefecture_id: @aichi.id)
  Municipality.create(name: '大府市', order_num: 1, prefecture_id: @aichi.id)
  Municipality.create(name: '知多市', order_num: 1, prefecture_id: @aichi.id)
  Municipality.create(name: '知立市', order_num: 1, prefecture_id: @aichi.id)
  Municipality.create(name: '尾張旭市', order_num: 1, prefecture_id: @aichi.id)
  Municipality.create(name: '高浜市', order_num: 1, prefecture_id: @aichi.id)
  Municipality.create(name: '岩倉市', order_num: 1, prefecture_id: @aichi.id)
  Municipality.create(name: '豊明市', order_num: 1, prefecture_id: @aichi.id)
  Municipality.create(name: '日進市', order_num: 1, prefecture_id: @aichi.id)
  Municipality.create(name: '田原市', order_num: 1, prefecture_id: @aichi.id)
  Municipality.create(name: '愛西市', order_num: 1, prefecture_id: @aichi.id)
  Municipality.create(name: '清須市', order_num: 1, prefecture_id: @aichi.id)
  Municipality.create(name: '北名古屋市', order_num: 1, prefecture_id: @aichi.id)
  Municipality.create(name: '弥富市', order_num: 1, prefecture_id: @aichi.id)
  Municipality.create(name: 'みよし市', order_num: 1, prefecture_id: @aichi.id)
  Municipality.create(name: 'あま市', order_num: 1, prefecture_id: @aichi.id)
  Municipality.create(name: '長久手市', order_num: 1, prefecture_id: @aichi.id)
  Municipality.create(name: '東郷町', order_num: 1, prefecture_id: @aichi.id)
  Municipality.create(name: '豊山町', order_num: 1, prefecture_id: @aichi.id)
  Municipality.create(name: '大口町', order_num: 1, prefecture_id: @aichi.id)
  Municipality.create(name: '扶桑町', order_num: 1, prefecture_id: @aichi.id)
  Municipality.create(name: '大治町', order_num: 1, prefecture_id: @aichi.id)
  Municipality.create(name: '蟹江町', order_num: 1, prefecture_id: @aichi.id)
  Municipality.create(name: '飛島村', order_num: 1, prefecture_id: @aichi.id)
  Municipality.create(name: '阿久比町', order_num: 1, prefecture_id: @aichi.id)
  Municipality.create(name: '東浦町', order_num: 1, prefecture_id: @aichi.id)
  Municipality.create(name: '南知多町', order_num: 1, prefecture_id: @aichi.id)
  Municipality.create(name: '美浜町', order_num: 1, prefecture_id: @aichi.id)
  Municipality.create(name: '武豊町', order_num: 1, prefecture_id: @aichi.id)
  Municipality.create(name: '幸田町', order_num: 1, prefecture_id: @aichi.id)
  Municipality.create(name: '設楽町', order_num: 1, prefecture_id: @aichi.id)
  Municipality.create(name: '東栄町', order_num: 1, prefecture_id: @aichi.id)
  Municipality.create(name: '豊根村', order_num: 1, prefecture_id: @aichi.id)

Prefecture.create(name: '三重', order_num: 24)
Prefecture.create(name: '滋賀', order_num: 25)
Prefecture.create(name: '京都', order_num: 26)
Prefecture.create(name: '大阪', order_num: 27)
Prefecture.create(name: '兵庫', order_num: 28)
Prefecture.create(name: '奈良', order_num: 29)
Prefecture.create(name: '和歌山', order_num: 30)
Prefecture.create(name: '鳥取', order_num: 31)
Prefecture.create(name: '島根', order_num: 32)
Prefecture.create(name: '岡山', order_num: 33)
Prefecture.create(name: '広島', order_num: 34)
Prefecture.create(name: '山口', order_num: 35)
Prefecture.create(name: '徳島', order_num: 36)
Prefecture.create(name: '香川', order_num: 37)
Prefecture.create(name: '愛媛', order_num: 38)
Prefecture.create(name: '高知', order_num: 39)
Prefecture.create(name: '福岡', order_num: 40)
Prefecture.create(name: '佐賀', order_num: 41)
Prefecture.create(name: '長崎', order_num: 42)
Prefecture.create(name: '熊本', order_num: 43)
Prefecture.create(name: '大分', order_num: 44)
Prefecture.create(name: '宮崎', order_num: 45)
Prefecture.create(name: '鹿児島', order_num: 46)
Prefecture.create(name: '沖縄', order_num: 47)